//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardeningWithMines.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5,0.5,0.5,0.5")]
        public global::System.Windows.Thickness BlockBorderThickness {
            get {
                return ((global::System.Windows.Thickness)(this["BlockBorderThickness"]));
            }
            set {
                this["BlockBorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MapRow {
            get {
                return ((int)(this["MapRow"]));
            }
            set {
                this["MapRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MapColumn {
            get {
                return ((int)(this["MapColumn"]));
            }
            set {
                this["MapColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double BlockFontSize {
            get {
                return ((double)(this["BlockFontSize"]));
            }
            set {
                this["BlockFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string BlockFontFamily {
            get {
                return ((string)(this["BlockFontFamily"]));
            }
            set {
                this["BlockFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public double BlockMaxFontSize {
            get {
                return ((double)(this["BlockMaxFontSize"]));
            }
            set {
                this["BlockMaxFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double GlobalHeight {
            get {
                return ((double)(this["GlobalHeight"]));
            }
            set {
                this["GlobalHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double GlobalWidth {
            get {
                return ((double)(this["GlobalWidth"]));
            }
            set {
                this["GlobalWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public double MapHeight {
            get {
                return ((double)(this["MapHeight"]));
            }
            set {
                this["MapHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public double MapWidth {
            get {
                return ((double)(this["MapWidth"]));
            }
            set {
                this["MapWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceCompleteView {
            get {
                return ((bool)(this["ForceCompleteView"]));
            }
            set {
                this["ForceCompleteView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double MaxViewMargin {
            get {
                return ((double)(this["MaxViewMargin"]));
            }
            set {
                this["MaxViewMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double MinBlockHeight {
            get {
                return ((double)(this["MinBlockHeight"]));
            }
            set {
                this["MinBlockHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double MinBlockWidth {
            get {
                return ((double)(this["MinBlockWidth"]));
            }
            set {
                this["MinBlockWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double DeltaHeight {
            get {
                return ((double)(this["DeltaHeight"]));
            }
            set {
                this["DeltaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double DeltaWidth {
            get {
                return ((double)(this["DeltaWidth"]));
            }
            set {
                this["DeltaWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public double FontSizeRatio {
            get {
                return ((double)(this["FontSizeRatio"]));
            }
            set {
                this["FontSizeRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSquareBlock {
            get {
                return ((bool)(this["IsSquareBlock"]));
            }
            set {
                this["IsSquareBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1")]
        public global::System.Windows.Thickness ExtraMapBorderThickness {
            get {
                return ((global::System.Windows.Thickness)(this["ExtraMapBorderThickness"]));
            }
            set {
                this["ExtraMapBorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MinesCount {
            get {
                return ((int)(this["MinesCount"]));
            }
            set {
                this["MinesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI Emoji")]
        public string IconFontFamily {
            get {
                return ((string)(this["IconFontFamily"]));
            }
            set {
                this["IconFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🚩")]
        public string FlagCharacter {
            get {
                return ((string)(this["FlagCharacter"]));
            }
            set {
                this["FlagCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double IconSizeRatio {
            get {
                return ((double)(this["IconSizeRatio"]));
            }
            set {
                this["IconSizeRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("💣")]
        public string MineCharacter {
            get {
                return ((string)(this["MineCharacter"]));
            }
            set {
                this["MineCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IconFontSize {
            get {
                return ((double)(this["IconFontSize"]));
            }
            set {
                this["IconFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public string BlockBackgroundBrush {
            get {
                return ((string)(this["BlockBackgroundBrush"]));
            }
            set {
                this["BlockBackgroundBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D0404040")]
        public string BlockForegroundBrush {
            get {
                return ((string)(this["BlockForegroundBrush"]));
            }
            set {
                this["BlockForegroundBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NeedNotToShowTips {
            get {
                return ((bool)(this["NeedNotToShowTips"]));
            }
            set {
                this["NeedNotToShowTips"] = value;
            }
        }
    }
}
